#include "common.h"

#include "VideoCapture.h"
#include "VideoWriter.h"

namespace ncv {

  namespace videoio {

    extern "C" void init(Local<Object> target) {
      Nan::HandleScope scope;

      // video capture apis
      DEFINE_CONST_ENUM(CAP_ANY);
      DEFINE_CONST_ENUM(CAP_VFW);
      DEFINE_CONST_ENUM(CAP_V4L);
      DEFINE_CONST_ENUM(CAP_V4L2);
      DEFINE_CONST_ENUM(CAP_FIREWIRE);
      DEFINE_CONST_ENUM(CAP_FIREWARE);
      DEFINE_CONST_ENUM(CAP_IEEE1394);
      DEFINE_CONST_ENUM(CAP_DC1394);
      DEFINE_CONST_ENUM(CAP_CMU1394);
      DEFINE_CONST_ENUM(CAP_QT);
      DEFINE_CONST_ENUM(CAP_UNICAP);
      DEFINE_CONST_ENUM(CAP_DSHOW);
      DEFINE_CONST_ENUM(CAP_PVAPI);
      DEFINE_CONST_ENUM(CAP_OPENNI);
      DEFINE_CONST_ENUM(CAP_OPENNI_ASUS);
      DEFINE_CONST_ENUM(CAP_ANDROID);
      DEFINE_CONST_ENUM(CAP_XIAPI);
      DEFINE_CONST_ENUM(CAP_AVFOUNDATION);
      DEFINE_CONST_ENUM(CAP_GIGANETIX);
      DEFINE_CONST_ENUM(CAP_MSMF);
      DEFINE_CONST_ENUM(CAP_WINRT);
      DEFINE_CONST_ENUM(CAP_INTELPERC);
      DEFINE_CONST_ENUM(CAP_OPENNI2);
      DEFINE_CONST_ENUM(CAP_OPENNI2_ASUS);
      DEFINE_CONST_ENUM(CAP_GPHOTO2);
      DEFINE_CONST_ENUM(CAP_GSTREAMER);
      DEFINE_CONST_ENUM(CAP_FFMPEG);
      DEFINE_CONST_ENUM(CAP_IMAGES);
      DEFINE_CONST_ENUM(CAP_ARAVIS);

      // video capture modes
      DEFINE_CONST_ENUM(CAP_MODE_BGR);
      DEFINE_CONST_ENUM(CAP_MODE_RGB);
      DEFINE_CONST_ENUM(CAP_MODE_GRAY);
      DEFINE_CONST_ENUM(CAP_MODE_YUYV);

      // video capture properties
      DEFINE_CONST_ENUM(CAP_PROP_POS_MSEC);
      DEFINE_CONST_ENUM(CAP_PROP_POS_FRAMES);
      DEFINE_CONST_ENUM(CAP_PROP_POS_AVI_RATIO);
      DEFINE_CONST_ENUM(CAP_PROP_FRAME_WIDTH);
      DEFINE_CONST_ENUM(CAP_PROP_FRAME_HEIGHT);
      DEFINE_CONST_ENUM(CAP_PROP_FPS);
      DEFINE_CONST_ENUM(CAP_PROP_FOURCC);
      DEFINE_CONST_ENUM(CAP_PROP_FRAME_COUNT);
      DEFINE_CONST_ENUM(CAP_PROP_FORMAT);
      DEFINE_CONST_ENUM(CAP_PROP_MODE);
      DEFINE_CONST_ENUM(CAP_PROP_BRIGHTNESS);
      DEFINE_CONST_ENUM(CAP_PROP_CONTRAST);
      DEFINE_CONST_ENUM(CAP_PROP_SATURATION);
      DEFINE_CONST_ENUM(CAP_PROP_HUE);
      DEFINE_CONST_ENUM(CAP_PROP_GAIN);
      DEFINE_CONST_ENUM(CAP_PROP_EXPOSURE);
      DEFINE_CONST_ENUM(CAP_PROP_CONVERT_RGB);
      DEFINE_CONST_ENUM(CAP_PROP_WHITE_BALANCE_BLUE_U);
      DEFINE_CONST_ENUM(CAP_PROP_RECTIFICATION);
      DEFINE_CONST_ENUM(CAP_PROP_MONOCHROME);
      DEFINE_CONST_ENUM(CAP_PROP_SHARPNESS);
      DEFINE_CONST_ENUM(CAP_PROP_AUTO_EXPOSURE);
      DEFINE_CONST_ENUM(CAP_PROP_GAMMA);
      DEFINE_CONST_ENUM(CAP_PROP_TEMPERATURE);
      DEFINE_CONST_ENUM(CAP_PROP_TRIGGER);
      DEFINE_CONST_ENUM(CAP_PROP_TRIGGER_DELAY);
      DEFINE_CONST_ENUM(CAP_PROP_WHITE_BALANCE_RED_V);
      DEFINE_CONST_ENUM(CAP_PROP_ZOOM);
      DEFINE_CONST_ENUM(CAP_PROP_FOCUS);
      DEFINE_CONST_ENUM(CAP_PROP_GUID);
      DEFINE_CONST_ENUM(CAP_PROP_ISO_SPEED);
      DEFINE_CONST_ENUM(CAP_PROP_BACKLIGHT);
      DEFINE_CONST_ENUM(CAP_PROP_PAN);
      DEFINE_CONST_ENUM(CAP_PROP_TILT);
      DEFINE_CONST_ENUM(CAP_PROP_ROLL);
      DEFINE_CONST_ENUM(CAP_PROP_IRIS);
      DEFINE_CONST_ENUM(CAP_PROP_SETTINGS);
      DEFINE_CONST_ENUM(CAP_PROP_BUFFERSIZE);
      DEFINE_CONST_ENUM(CAP_PROP_AUTOFOCUS);

      // video writer properties
      DEFINE_CONST_ENUM(VIDEOWRITER_PROP_QUALITY);
      DEFINE_CONST_ENUM(VIDEOWRITER_PROP_FRAMEBYTES);
      DEFINE_CONST_ENUM(VIDEOWRITER_PROP_NSTRIPES);

      VideoCapture::Init(target);
      VideoWriter::Init(target);
    }

    NODE_MODULE(videoio, init);
  }

}
